# Whatsapp Chat Analysis Project

In [1]:
import re
import pandas as pd

In [3]:
f = open("chat.txt", "r", encoding="utf-8")

In [5]:
data = f.read()

In [6]:
print(data)

# converted into data fram
# 1 data
# 2 message

In [10]:
# data time pattern
pattern = '\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s-\s'

In [11]:
messages = re.split(pattern, data)

In [12]:
messages

['']

In [13]:
messages = messages[1:]
# first text is empyts

In [14]:
messages

[]

In [15]:
dates = re.findall(pattern, data)

In [16]:
dates

[]

# data frame

In [17]:
pd.DataFrame({'user_message': messages, 'message_date': dates})

Empty DataFrame
Columns: [user_message, message_date]
Index: []

In [18]:
df = pd.DataFrame({'user_message': messages, 'message_date': dates})
df

Empty DataFrame
Columns: [user_message, message_date]
Index: []

# date time format converted

In [19]:
df["message_date"] = pd.to_datetime(df["message_date"], format="%d/%m/%y, %H:%M - ")

In [20]:
df

Empty DataFrame
Columns: [user_message, message_date]
Index: []

In [21]:
df["message_date"]

Series([], Name: message_date, dtype: datetime64[ns])

In [22]:
df.shape

(0, 2)

create a 3 columns
date
user
messages

In [23]:
df.rename(columns={"message_date": "date"}, inplace=True)

In [24]:
users = []
messages = []
for message in df["user_message"]:
  entry = re.split("([\w\W]+?):\s", message)
  if entry[1:]:
    users.append(entry[1])
    messages.append(entry[2])
  else:
    users.append("group_notification")
    messages.append(entry[0])

df['user'] = users
df['message'] = messages
df.drop(columns=["user_message"], inplace=True)

In [25]:
df

Empty DataFrame
Columns: [date, user, message]
Index: []

create 5 columns
year
months
day
hours
minutes

In [26]:
df["year"] = df["date"].dt.year
df["month"] = df["date"].dt.month_name()
df["day"] = df["date"].dt.day
df["hour"] = df["date"].dt.hour
df["minutes"] = df["date"].dt.minute

In [27]:
df

Empty DataFrame
Columns: [date, user, message, year, month, day, hour, minutes]
Index: []